<a href="https://colab.research.google.com/github/Deesha-sekar/CODSOFT/blob/main/tpa01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# 1. Create a NumPy 2D array containing marks for 10 students (10 students, 4 subjects)
marks = np.random.randint(35, 100, size=(10, 4))

# 2. Display the complete marks array
print("2. Complete Marks Array:\n", marks)

# 3. Display the marks of the first 5 students
print("\n3. Marks of the First 5 Students:\n", marks[:5])

# 4. Display the marks of the Python subject for all students (assuming Column 0 is Python)
print("\n4. Python Marks for All Students:\n", marks[:, 0])

# 5. Display the marks of the first student
print("\n5. Marks of First Student:\n", marks[0])

# 6. Find the total marks obtained by each student
total_marks = np.sum(marks, axis=1)
print("\n6. Total Marks of Each Student:\n", total_marks)

# 7. Find the average marks of each student
avg_marks = np.mean(marks, axis=1)
print("\n7. Average Marks of Each Student:\n", avg_marks)

# 8. Find the highest mark in each subject
print("\n8. Highest Mark in Each Subject:\n", np.max(marks, axis=0))

# 9. Find the lowest mark in each subject
print("\n9. Lowest Mark in Each Subject:\n", np.min(marks, axis=0))

# 10. Find the overall highest mark in the entire array
print("\n10. Overall Highest Mark:", np.max(marks))

# 11. Find the overall lowest mark in the entire array
print("\n11. Overall Lowest Mark:", np.min(marks))

# 12. Find students whose average is greater than 75
students_avg_gt_75 = np.where(avg_marks > 75)[0]
print("\n12. Student Indices with Average > 75:", students_avg_gt_75)

# 13. Find students whose Python mark is greater than 80
students_python_gt_80 = np.where(marks[:, 0] > 80)[0]
print("\n13. Student Indices with Python Mark > 80:", students_python_gt_80)

# 14. Count how many students have an average greater than or equal to 60
count_avg_gte_60 = np.sum(avg_marks >= 60)
print("\n14. Number of Students with Average >= 60:", count_avg_gte_60)

# 15. Replace all marks below 40 with 40
marks_replaced = marks.copy()
marks_replaced[marks_replaced < 40] = 40
print("\n15. Array after Replacing Marks Below 40 with 40:\n", marks_replaced)

# 16. Reshape the array if possible and display the new shape
reshaped_marks = marks.reshape(5, 8)
print("\n16. Reshaped Array (5x8):\n", reshaped_marks)
print("    New Shape:", reshaped_marks.shape)

# 17. Display array parameters
print("\n17. Array Parameters:")
print("  - Number of students:", marks.shape[0])
print("  - Number of subjects:", marks.shape[1])
print("  - Shape of the array:", marks.shape)
print("  - Size of the array:", marks.size)

# --- Additional Questions ---

# 1. Calculate the mean, median, and standard deviation of the complete marks array
print("\n--- Additional Questions ---")
print(f"1. Mean: {np.mean(marks):.2f}")
print(f"   Median: {np.median(marks):.2f}")
print(f"   Standard Deviation: {np.std(marks):.2f}")

# 2. Sort the marks of each student
sorted_marks = np.sort(marks, axis=1)
print("\n2. Sorted Marks of Each Student (Row-wise):\n", sorted_marks)

# 3. Find the student with the highest total marks
top_student = np.argmax(total_marks)
print(f"\n3. Student Index with Highest Total Marks: Student {top_student} (Total: {total_marks[top_student]})")

2. Complete Marks Array:
 [[86 49 95 55]
 [58 37 56 87]
 [36 64 72 36]
 [98 94 55 67]
 [92 56 83 93]
 [76 94 49 96]
 [96 81 96 85]
 [89 98 37 85]
 [41 55 73 52]
 [38 94 48 43]]

3. Marks of the First 5 Students:
 [[86 49 95 55]
 [58 37 56 87]
 [36 64 72 36]
 [98 94 55 67]
 [92 56 83 93]]

4. Python Marks for All Students:
 [86 58 36 98 92 76 96 89 41 38]

5. Marks of First Student:
 [86 49 95 55]

6. Total Marks of Each Student:
 [285 238 208 314 324 315 358 309 221 223]

7. Average Marks of Each Student:
 [71.25 59.5  52.   78.5  81.   78.75 89.5  77.25 55.25 55.75]

8. Highest Mark in Each Subject:
 [98 98 96 96]

9. Lowest Mark in Each Subject:
 [36 37 37 36]

10. Overall Highest Mark: 98

11. Overall Lowest Mark: 36

12. Student Indices with Average > 75: [3 4 5 6 7]

13. Student Indices with Python Mark > 80: [0 3 4 6 7]

14. Number of Students with Average >= 60: 6

15. Array after Replacing Marks Below 40 with 40:
 [[86 49 95 55]
 [58 40 56 87]
 [40 64 72 40]
 [98 94 55 67]
 [92